/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.somi92.snakepitui.dialogs;

import javax.swing.JOptionPane;
import clojure_snake.core;
/**
 *
 * @author milos
 */
public class LoadRunDialog extends javax.swing.JDialog {

    /**
     * Creates new form LoadRunDialog
     */
    public LoadRunDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtRoutine = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jbtnDemo = new javax.swing.JButton();
        jbtnRun = new javax.swing.JButton();
        jbtnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Load and run snake");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtxtRoutine.setColumns(20);
        jtxtRoutine.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jtxtRoutine.setLineWrap(true);
        jtxtRoutine.setRows(5);
        jScrollPane1.setViewportView(jtxtRoutine);

        jLabel1.setText("Enter control routine or use demo:");

        jbtnDemo.setText("Load demo");
        jbtnDemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDemoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnDemo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDemo)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtnRun.setText("Run snake");
        jbtnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRunActionPerformed(evt);
            }
        });

        jbtnClear.setText("Clear routine");
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnRun, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnRun, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDemoActionPerformed
        String demo = "(if-danger-ahead\n" +
" (if-danger-ahead\n" +
"  (if-danger-two-ahead\n" +
"   (if-danger-left (turn-right) (turn-left))\n" +
"   (turn-right))\n" +
"  (if-food-up\n" +
"   (if-food-right (move-forward) (move-forward))\n" +
"   (if-danger-two-ahead\n" +
"    (if-danger-left (turn-right) (turn-left))\n" +
"    (turn-left))))\n" +
" (if-danger-right\n" +
"  (if-moving-up\n" +
"   (if-moving-up\n" +
"    (if-food-up\n" +
"     (if-food-right (move-forward) (move-forward))\n" +
"     (if-danger-right (turn-left) (turn-right)))\n" +
"    (if-danger-ahead\n" +
"     (if-food-up (move-forward) (turn-right))\n" +
"     (if-moving-right (turn-right) (turn-right))))\n" +
"   (if-food-ahead (move-forward) (move-forward)))\n" +
"  (if-moving-down\n" +
"   (turn-left)\n" +
"   (if-food-right\n" +
"    (if-moving-right\n" +
"     (if-food-up (move-forward) (turn-left))\n" +
"     (if-moving-down (move-forward) (turn-right)))\n" +
"    (if-danger-ahead\n" +
"     (if-moving-right (move-forward) (turn-right))\n" +
"     (if-moving-right (turn-left) (move-forward)))))))";
        
        jtxtRoutine.setText(demo);
    }//GEN-LAST:event_jbtnDemoActionPerformed

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
        jtxtRoutine.setText("");
    }//GEN-LAST:event_jbtnClearActionPerformed

    private void jbtnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRunActionPerformed
        String routine = jtxtRoutine.getText().trim();
        if(routine == null || routine.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Cannot load empty routine.");
        } else {
            dispose();
            String res = core.game(routine, 50);
            System.out.println(res);
        }
    }//GEN-LAST:event_jbtnRunActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnDemo;
    private javax.swing.JButton jbtnRun;
    private javax.swing.JTextArea jtxtRoutine;
    // End of variables declaration//GEN-END:variables
}
